# Generated by Django 4.2.15 on 2024-10-04 12:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Eyetrack', '0002_gazetrackingresult_result_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='gazetrackingresult',
            old_name='encoded_image',
            new_name='image_url',
        ),
        migrations.RemoveField(
            model_name='gazetrackingresult',
            name='result_image',
        ),
    ]
