# Generated by Django 4.2.15 on 2024-09-30 12:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('QuestionList', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='VoiceAnalysis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pitch_graph', models.TextField(blank=True, null=True)),
                ('intensity_graph', models.TextField(blank=True, null=True)),
                ('pitch_summary', models.CharField(blank=True, max_length=255, null=True)),
                ('intensity_summary', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('question_list', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='QuestionList.questionlists')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='InterviewAnalysis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('response_1', models.TextField(blank=True, null=True)),
                ('redundancies_1', models.TextField(blank=True, null=True)),
                ('inappropriateness_1', models.TextField(blank=True, null=True)),
                ('corrections_1', models.TextField(blank=True, null=True)),
                ('corrected_response_1', models.TextField(blank=True, null=True)),
                ('response_2', models.TextField(blank=True, null=True)),
                ('redundancies_2', models.TextField(blank=True, null=True)),
                ('inappropriateness_2', models.TextField(blank=True, null=True)),
                ('corrections_2', models.TextField(blank=True, null=True)),
                ('corrected_response_2', models.TextField(blank=True, null=True)),
                ('response_3', models.TextField(blank=True, null=True)),
                ('redundancies_3', models.TextField(blank=True, null=True)),
                ('inappropriateness_3', models.TextField(blank=True, null=True)),
                ('corrections_3', models.TextField(blank=True, null=True)),
                ('corrected_response_3', models.TextField(blank=True, null=True)),
                ('response_4', models.TextField(blank=True, null=True)),
                ('redundancies_4', models.TextField(blank=True, null=True)),
                ('inappropriateness_4', models.TextField(blank=True, null=True)),
                ('corrections_4', models.TextField(blank=True, null=True)),
                ('corrected_response_4', models.TextField(blank=True, null=True)),
                ('response_5', models.TextField(blank=True, null=True)),
                ('redundancies_5', models.TextField(blank=True, null=True)),
                ('inappropriateness_5', models.TextField(blank=True, null=True)),
                ('corrections_5', models.TextField(blank=True, null=True)),
                ('corrected_response_5', models.TextField(blank=True, null=True)),
                ('response_6', models.TextField(blank=True, null=True)),
                ('redundancies_6', models.TextField(blank=True, null=True)),
                ('inappropriateness_6', models.TextField(blank=True, null=True)),
                ('corrections_6', models.TextField(blank=True, null=True)),
                ('corrected_response_6', models.TextField(blank=True, null=True)),
                ('response_7', models.TextField(blank=True, null=True)),
                ('redundancies_7', models.TextField(blank=True, null=True)),
                ('inappropriateness_7', models.TextField(blank=True, null=True)),
                ('corrections_7', models.TextField(blank=True, null=True)),
                ('corrected_response_7', models.TextField(blank=True, null=True)),
                ('response_8', models.TextField(blank=True, null=True)),
                ('redundancies_8', models.TextField(blank=True, null=True)),
                ('inappropriateness_8', models.TextField(blank=True, null=True)),
                ('corrections_8', models.TextField(blank=True, null=True)),
                ('corrected_response_8', models.TextField(blank=True, null=True)),
                ('response_9', models.TextField(blank=True, null=True)),
                ('redundancies_9', models.TextField(blank=True, null=True)),
                ('inappropriateness_9', models.TextField(blank=True, null=True)),
                ('corrections_9', models.TextField(blank=True, null=True)),
                ('corrected_response_9', models.TextField(blank=True, null=True)),
                ('response_10', models.TextField(blank=True, null=True)),
                ('redundancies_10', models.TextField(blank=True, null=True)),
                ('inappropriateness_10', models.TextField(blank=True, null=True)),
                ('corrections_10', models.TextField(blank=True, null=True)),
                ('corrected_response_10', models.TextField(blank=True, null=True)),
                ('overall_feedback', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('question_list', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='QuestionList.questionlists')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
