# Generated by Django 4.2.15 on 2024-09-30 12:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('InterviewAnalyze', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='voiceanalysis',
            table='VoiceAnalysis',
        ),
    ]
