# Generated by Django 4.2.15 on 2024-09-30 18:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('InterviewAnalyze', '0002_alter_voiceanalysis_table'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='voiceanalysis',
            table='voicerecording',
        ),
    ]
