# Generated by Django 4.2.15 on 2024-09-30 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('InterviewAnalyze', '0004_alter_voiceanalysis_table'),
    ]

    operations = [
        migrations.AddField(
            model_name='voiceanalysis',
            name='intensity_summary4',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='voiceanalysis',
            name='pitch_summary4',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
