# Generated by Django 4.2.15 on 2024-09-30 18:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('InterviewAnalyze', '0005_voiceanalysis_intensity_summary4_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='VoiceAnalysis',
        ),
    ]
