# Generated by Django 4.2.15 on 2024-09-30 19:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('QuestionList', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('InterviewAnalyze', '0006_delete_voiceanalysis'),
    ]

    operations = [
        migrations.CreateModel(
            name='VoiceAnalysis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pitch_graph', models.TextField(blank=True, null=True)),
                ('intensity_graph', models.TextField(blank=True, null=True)),
                ('pitch_summary', models.CharField(blank=True, max_length=255, null=True)),
                ('intensity_summary', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('question_list', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='QuestionList.questionlists')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
